name: deploy_firebase_hosting
on:
  push:
    branches:
      - main
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
	# ポイント１
	# ↓↓↓ node_modulesはgit管理していないと思いますので、ここで、nodeモジュールを取得するコマンドをjobとして設定します。
      - name: Install Dependencies # ← コマンド識別名
        run: yarn install　# ← 実際のコマンド
	# ポイント２
	# ↓↓↓ ビルドファイルを作成するためのコマンド
      - name: Build
        run: yarn build
	# ポイント３
	# ↓↓↓ Firebaseのデプロイコマンドここに先ほど控えたトークンを貼り付けます
      - name: Deploy to Firebase
        run: yarn deploy --token "1//0e8l0crpLk0ouCgYIARAAGA4SNwF-L9IrSL5zyhXYYm6SpOHEb7G4uAdOqJWRVph8ItBUGpo206nF21YYqQOBB_TmjbIVRQwL2qg"
