name: deploy_firebase_hosting
on:
  push:
    branches:
      - main
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        run: yarn deploy --token "1//0e8l0crpLk0ouCgYIARAAGA4SNwF-L9IrSL5zyhXYYm6SpOHEb7G4uAdOqJWRVph8ItBUGpo206nF21YYqQOBB_TmjbIVRQwL2qg"
